Budget app project
AlyAtalla/budget-app pull request #2
Opened 2023-11-27 10:16 UTC by AlyAtalla

welcome to ROR Capstone Project: budget-app

Project requirements
Design
You should follow these [design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), including:
Colors.
Typography: font face, size and weight.
Layout: composition and space between elements.
Interactions
 Splash screen
A simple page with the name of your app (yes, you need to choose one), and links to the sign up and log in pages.
Sign up and log in pages

The user should be able to register in the app with full name, email and password (all mandatory).

The user can log into the app using email and password.

If the user is not logged in, they can't access pages that require the user to be logged in (all the pages described below).

 Home page (categories page)

When the user logs in, they are presented with the categories page.

For each category, the user can see their name, icon and the total amount of all the transactions that belongs to that category.

When the user clicks (or taps) on a category item, the application navigates to the transactions page for that category.

There is a button "add a new category" at the bottom that brings the user to the page to create a new category.

 Transactions page

For a given category, the list of transactions is presented, ordered by the most recent.

At the top of the page the user could see the total amount for the category (sum of all of the amounts of the transactions in that category).

There is a button "add a new transaction" at the bottom that brings the user to the page to create a new transaction.

When the user clicks on the "Back" button (<), the user navigates to the home page.

 "Add a new category" page

The user fills out a form to create a new category, indicating their name and icon (both mandatory).

The user clicks (or taps) the "Save" button to create the new category, and is taken to the home page on success.

When the user clicks on the "Back" button (<), the user navigates to the home page.

 "Add a new transaction" page

The user fills out a form to create a new transaction with:

name (mandatory)

amount (mandatory)

categories (mandatory at least one)

The user click (or taps) the "Save" button to create the new transaction, and is taken to the transactions page for that category.

When the user clicks on the "Back" button (<), the user navigates to the transactions page for that category.

 Testing requirements
Create unit and integration tests for all the most important components of your RoR application.
Screenshot (546)

 Technical requirements

You should use Postgres as your database.

You should use devise for authentication.

You should validate all user input to make sure that anyone with bad intentions cannot compromise your app.

You can use a view template engine of your choice (.erb, .slim, .haml).

The project should be deployed and accessible online.

Your database schema should reflect the following structure:

 Project documentation
Record a video presenting the features of the project you built. It is a video with a maximum length of 5 minutes. The content of the video should include:

a description of the project.

a demo of the project features.

you should also highlight some interesting piece of code or something you built that you are very proud of.

 Deploy the project.

 Additional requirements

implement some UX improvements: include transitions and/or animations, etc.

Have a decent desktop design for the webapp.

Implement Delete so that users can delete their own category.

Implement Delete so that users can delete their own Exchange.

Implement an update so that users can update their own category.

Implement an update so that users can update their own Exchange.

2023-11-27 18:53 UTC, DammyShittu requested changes
Hi @AlyAtalla,

## Highlights
✔️ Splash screen
✔️ Positioned new categories and transactions buttons
✔️ Ordered transactions by most recent

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-27 18:53 UTC, DammyShittu commented on README.md
> +
- [ ] Kindly deploy your app and provide its live demo link on the readme documentation.

- [ ] Kindly make a presentation of your app, preferably on Loom, demonstrating features of the app. The video should not be more than 5 minutes long and kindly also highlight code or feature you find interesting.

2023-11-27 18:53 UTC, DammyShittu commented on app/views/exchanges/new.html.erb
> +    <a href="/" class="navbar-item">
- [ ] When a user is on the add new transaction form page, and they click the arrow "back" button (<) they should be taken to the transactions index page of the category, not the category page or root page.

  ![image](https://github.com/AlyAtalla/budget-app/assets/54848363/fb546404-f2df-4068-bb60-1d0c1dca4a56)

2023-11-27 18:53 UTC, DammyShittu commented on app/views/exchanges/index.html.erb
> +    </div>
- [ ] The transactions on the transactions index page should be redesigned to match the design. You should indicate the time the item was created and include some kind of image to maintain the positioning of elements as requested in the project.

  Your Implementation | Behance Design
  :---:|:---:
  ![image](https://github.com/AlyAtalla/budget-app/assets/54848363/bde8c418-545e-44f7-a678-b39ec60099ae) | ![image](https://github.com/AlyAtalla/budget-app/assets/54848363/ac0d7b31-5900-4564-a60c-5a456dca28f0)

2023-11-27 18:53 UTC, DammyShittu commented on spec/integration/index_spec.rb
> +end
- [ ] You only have unit model tests. You have no integration tests. Kindly add enough integration tests to cover several combinations of user actions in your app.

2023-11-29 08:51 UTC, binhussen approved these changes
Hi @AlyAtalla , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
![IApproveSimonCowellGIF (6)](https://github.com/AlyAtalla/budget-app/assets/52010789/6526ace7-5c90-496b-8196-95bafb13b2b1)

## Highlights
- Sticked Given Design ✔️
- Well Stractured Code ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-29 08:52 UTC, merged